AppBundle\Entity\NoteEntity:
  exclusion_policy: ALL
  xml_root_name: note
  properties:
    id:
      expose: true
      type: string
      accessor: # access_type must be set to public_method
                getter: getId
      groups: [standard, restapi]
    message:
      exclude: true
      expose: true
      access_type: public_method # defaults to property
      accessor: # access_type must be set to public_method
          getter: getMessage
          setter: setMessage
      type: string
      groups: [standard, restapi]
    secret:
      exclude: true
      expose: true
      access_type: public_method # defaults to property
      accessor: # access_type must be set to public_method
          getter: getSecret
          setter: setSecret
      type: string
      groups: [restapi]
    version:
      expose: true
      type: string
      until_version: 1.1
    new_version:
      expose: true
      type: string
      serialized_name: version
      since_version: 1.1
    urls:
      expose: true
      type: string
      groups: [standard, restapi]
  relations:
    -
      rel: self
      href:
        route: get_note
        parameters:
          id: expr(object.id)
        absolute: true
    -
      rel: expr(object.getAssociatedEventsRel())
      embed:
        content: expr(object.getAssociatedEvents())
        xmlElementName: events
        exclusion:
          exclude_if: expr(object.id === 0)
